{
    "errors": [
        "Please read about usage of __all__ in python modules and not just add __all__ with arrays with all variables in module",
        "169883-mishaveret-course-1187/lyceum/about/apps.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/about/tests.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/about/views.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/catalog/admin.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/catalog/apps.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/catalog/converters.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/catalog/models.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/catalog/models.py:59:13: T201 print found.",
        "169883-mishaveret-course-1187/lyceum/catalog/tests.py:1:1: DALL000 Module lacks __all__.",
        '169883-mishaveret-course-1187/lyceum/catalog/tests.py:395:38: A002 argument "input" is shadowing a Python builtin',
        '169883-mishaveret-course-1187/lyceum/catalog/tests.py:401:40: A002 argument "input" is shadowing a Python builtin',
        "169883-mishaveret-course-1187/lyceum/catalog/validators.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/catalog/views.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/core/apps.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/core/models.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/homepage/apps.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/homepage/tests.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/homepage/views.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/lyceum/middleware.py:1:1: DALL000 Module lacks __all__.",
        "169883-mishaveret-course-1187/lyceum/lyceum/tests.py:1:1: DALL000 Module lacks __all__.",
        "Too few catalog migrations, did you delete old migrations?",
        "No inlines in admin",
        "No static bootstrap in the base template",
        "No reverse url in tests",
        "No reverse url in tests or it has no app name",
        "Some of your tests is failing. Test report is attached",
        "Some of your tests is failing. Test report is attached",
        "Collecting Django==4.2.16",
        " Using cached Django-4.2.16-py3-none-any.whl (8.0 MB)",
        "Collecting django-cleanup==9.0.0",
        " Using cached django_cleanup-9.0.0-py3-none-any.whl (10 kB)",
        "Collecting pillow==11.0.0",
        " Using cached pillow-11.0.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.4 MB)",
        "Collecting python-dotenv==1.0.1",
        " Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)",
        "Collecting sorl-thumbnail==12.11.0",
        " Using cached sorl_thumbnail-12.11.0-py3-none-any.whl (42 kB)",
        "Collecting sqlparse>=0.3.1",
        " Using cached sqlparse-0.5.1-py3-none-any.whl (44 kB)",
        "Collecting asgiref<4,>=3.6.0",
        " Using cached asgiref-3.8.1-py3-none-any.whl (23 kB)",
        "Collecting typing-extensions>=4",
        " Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)",
        "Installing collected packages: typing-extensions, sqlparse, sorl-thumbnail, python-dotenv, pillow, django-cleanup, asgiref, Django",
        "Successfully installed Django-4.2.16 asgiref-3.8.1 django-cleanup-9.0.0 pillow-11.0.0 python-dotenv-1.0.1 sorl-thumbnail-12.11.0 sqlparse-0.5.1 typing-extensions-4.12.2",
        "Requirement already satisfied: Django==4.2.16 in ./venv/lib/python3.10/site-packages (from -r requirements/prod.txt (line 1)) (4.2.16)",
        "Requirement already satisfied: django-cleanup==9.0.0 in ./venv/lib/python3.10/site-packages (from -r requirements/prod.txt (line 2)) (9.0.0)",
        "Requirement already satisfied: pillow==11.0.0 in ./venv/lib/python3.10/site-packages (from -r requirements/prod.txt (line 3)) (11.0.0)",
        "Requirement already satisfied: python-dotenv==1.0.1 in ./venv/lib/python3.10/site-packages (from -r requirements/prod.txt (line 4)) (1.0.1)",
        "Requirement already satisfied: sorl-thumbnail==12.11.0 in ./venv/lib/python3.10/site-packages (from -r requirements/prod.txt (line 5)) (12.11.0)",
        "Collecting django-debug-toolbar==4.4.6",
        " Using cached django_debug_toolbar-4.4.6-py3-none-any.whl (229 kB)",
        "Collecting flake8-commas==4.0.0",
        " Using cached flake8_commas-4.0.0-py3-none-any.whl (7.9 kB)",
        "Collecting flake8-import-order==0.18.2",
        " Using cached flake8_import_order-0.18.2-py2.py3-none-any.whl (15 kB)",
        "Collecting flake8-quotes==3.4.0",
        " Using cached flake8_quotes-3.4.0-py3-none-any.whl",
        "Collecting parameterized==0.9.0",
        " Using cached parameterized-0.9.0-py2.py3-none-any.whl (20 kB)",
        "Collecting pep8-naming==0.14.1",
        " Using cached pep8_naming-0.14.1-py3-none-any.whl (8.9 kB)",
        "Requirement already satisfied: sqlparse>=0.3.1 in ./venv/lib/python3.10/site-packages (from Django==4.2.16->-r requirements/prod.txt (line 1)) (0.5.1)",
        "Requirement already satisfied: asgiref<4,>=3.6.0 in ./venv/lib/python3.10/site-packages (from Django==4.2.16->-r requirements/prod.txt (line 1)) (3.8.1)",
        "Collecting flake8>=5",
        " Using cached flake8-7.1.1-py2.py3-none-any.whl (57 kB)",
        "Collecting pycodestyle",
        " Using cached pycodestyle-2.12.1-py2.py3-none-any.whl (31 kB)",
        "Requirement already satisfied: setuptools in ./venv/lib/python3.10/site-packages (from flake8-import-order==0.18.2->-r requirements/test.txt (line 5)) (58.1.0)",
        "Requirement already satisfied: typing-extensions>=4 in ./venv/lib/python3.10/site-packages (from asgiref<4,>=3.6.0->Django==4.2.16->-r requirements/prod.txt (line 1)) (4.12.2)",
        "Collecting mccabe<0.8.0,>=0.7.0",
        " Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)",
        "Collecting pyflakes<3.3.0,>=3.2.0",
        " Using cached pyflakes-3.2.0-py2.py3-none-any.whl (62 kB)",
        "Installing collected packages: pyflakes, pycodestyle, parameterized, mccabe, flake8-import-order, flake8, pep8-naming, flake8-quotes, flake8-commas, django-debug-toolbar",
        "Successfully installed django-debug-toolbar-4.4.6 flake8-7.1.1 flake8-commas-4.0.0 flake8-import-order-0.18.2 flake8-quotes-3.4.0 mccabe-0.7.0 parameterized-0.9.0 pep8-naming-0.14.1 pycodestyle-2.12.1 pyflakes-3.2.0",
        "Requirement already satisfied: parameterized in ./venv/lib/python3.10/site-packages (0.9.0)",
        "Found 59 test(s).",
        "System check identified no issues (0 silenced).",
        "WARNING: You are using pip version 22.0.4; however, version 24.2 is available.",
        "You should consider upgrading via the '/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/bin/python3 -m pip install --upgrade pip' command.",
        "WARNING: You are using pip version 22.0.4; however, version 24.2 is available.",
        "You should consider upgrading via the '/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/bin/python3 -m pip install --upgrade pip' command.",
        "WARNING: You are using pip version 22.0.4; however, version 24.2 is available.",
        "You should consider upgrading via the '/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/bin/python3 -m pip install --upgrade pip' command.",
        "Creating test database for alias 'default'...",
        "..............................................E............",
        "======================================================================",
        "ERROR: test_catalog_item_endpoint_01_100 (catalog.tests.StaticURLTests)",
        "----------------------------------------------------------------------",
        "Traceback (most recent call last):",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func',
        " return func(*(a + p.args), **p.kwargs, **kw)",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/lyceum/catalog/tests.py", line 31, in test_catalog_item_endpoint',
        " response = django.test.Client().get(f'/catalog/{url}/')",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/django/test/client.py", line 927, in get',
        " response = super().get(path, data=data, secure=secure, headers=headers, **extra)",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/django/test/client.py", line 457, in get',
        " return self.generic(",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/django/test/client.py", line 609, in generic',
        " return self.request(**r)",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/django/test/client.py", line 891, in request',
        " self.check_exception(response)",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/django/test/client.py", line 738, in check_exception',
        " raise exc_value",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner',
        " response = get_response(request)",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response',
        " response = wrapped_callback(request, *callback_args, **callback_kwargs)",
        ' File "/builds/13/1/19343043/checker/169883-mishaveret-course-1187/lyceum/catalog/views.py", line 59, in item_detail',
        ' context={"item": context[elem - 1]},',
        "IndexError: list index out of range",
        "----------------------------------------------------------------------",
        "Ran 59 tests in 0.282s",
        "FAILED (errors=1)",
        "Destroying test database for alias 'default'...",
        "Some errors while running in PROD mode and getting requests",
        'Wrong content for `http://localhost:8432/`: expected b\'\\xd0\\x93\\xd0\\xbb\\xd0\\xb0\\xd0\\xb2\\xd0\\xbd\\xd0\\xb0\\xd1\\x8f\' in content, got \n\n<!DOCTYPE html>\n<html lang="ru">\n\n <head>\n \n <meta charset="utf-8">\n <meta name="viewport" content="width=device-width, initial-scale=1">\n \n <link rel="stylesheet" href="/static/css/bootstrap.css">\n\n <link rel="icon" type="image" href="/static/files/favicon.ico" sizes="48x48" />\n <link rel="icon" type="image/svg+xml" href="/static/files/favicon.svg" />\n <link rel="shortcut icon" href="/static/files/favicon.ico" />\n <link rel="apple-touch-icon" sizes="180x180" href="/static/files/apple-touch-icon.png" />\n <link rel="manifest" href="/static/files/site.webmanifest" />\n\n <title>Django проект</title>\n\n\n </head>\n\n <body>\n\n\n \n\n<header>\n <nav class="navbar navbar-light bg-light">\n \n \n <ul class="nav justify-content-center">\n\n <a href="/">\n <img src="/static/files/favicon-48x48.png" class="d-inline-block align-right" alt="">\n </a>\n\n <li class="nav-item">\n <a class="nav-link disabled" href="/">На главную</a>\n </li>\n <li class="nav-item">\n <a class="nav-link " href="/about/">О проекте</a>\n </li>\n <li class="nav-item">\n <a class="nav-link " href="/catalog/">Список товаров</a>\n </li>\n </ul>\n \n\n\n </nav>\n \n\n \n\n</header>\n\n\n <main>\n \n <div class="m-1">\n <img style="max-width: 15%;" src="/static/img/raccoon.jpg">\n </div>\n \n\n \n \n <br>\n \n <div class="row m-2">\n \n \n <div class="card me-2" style="width: 12rem;">\n <img class="card-img-top" src="/static/img/rubic.jpg">\n <div class="card-body">\n <h5 class="card-title">Кубик рубика</h5>\n <p class="card-text">Хороший тренажер мозга</p>\n <a href="/catalog/1/" class="btn btn-primary">Подробнее</a>\n </div>\n </div>\n \n <div class="card me-2" style="width: 12rem;">\n <img class="card-img-top" src="/static/img/keyboard.jpg">\n <div class="card-body">\n <h5 class="card-title">Клавиатура</h5>\n <p class="card-text">Бюджетная механическая клавиатура</p>\n <a href="/catalog/2/" class="btn btn-primary">Подробнее</a>\n </div>\n </div>\n \n <div class="card me-2" style="width: 12rem;">\n <img class="card-img-top" src="/static/img/borjomi.jpg">\n <div class="card-body">\n <h5 class="card-title">Боржоми</h5>\n <p class="card-text">Поздно Вася пить боржоми когда почки отказали</p>\n <a href="/catalog/3/" class="btn btn-primary">Подробнее</a>\n </div>\n </div>\n \n\n </div>\n\n \n\n\n\n </main>\n\n \n\n<footer>\n <div class="navbar navbar-light bg-light fixed-bottom">\n <p> © 2024 Mike Veretennikov </p>\n </div>\n</footer>\n\n </body> \n\n</html>',
        "Some errors while running in PROD mode and getting requests",
        'Wrong content for `http://127.0.0.1:8442/`: expected b\'\\xd0\\x93\\xd0\\xbb\\xd0\\xb0\\xd0\\xb2\\xd0\\xbd\\xd0\\xb0\\xd1\\x8f\' in content, got \n\n<!DOCTYPE html>\n<html lang="ru">\n\n <head>\n \n <meta charset="utf-8">\n <meta name="viewport" content="width=device-width, initial-scale=1">\n \n <link rel="stylesheet" href="/static/css/bootstrap.css">\n\n <link rel="icon" type="image" href="/static/files/favicon.ico" sizes="48x48" />\n <link rel="icon" type="image/svg+xml" href="/static/files/favicon.svg" />\n <link rel="shortcut icon" href="/static/files/favicon.ico" />\n <link rel="apple-touch-icon" sizes="180x180" href="/static/files/apple-touch-icon.png" />\n <link rel="manifest" href="/static/files/site.webmanifest" />\n\n <title>Django проект</title>\n\n\n </head>\n\n <body>\n\n\n \n\n<header>\n <nav class="navbar navbar-light bg-light">\n \n \n <ul class="nav justify-content-center">\n\n <a href="/">\n <img src="/static/files/favicon-48x48.png" class="d-inline-block align-right" alt="">\n </a>\n\n <li class="nav-item">\n <a class="nav-link disabled" href="/">На главную</a>\n </li>\n <li class="nav-item">\n <a class="nav-link " href="/about/">О проекте</a>\n </li>\n <li class="nav-item">\n <a class="nav-link " href="/catalog/">Список товаров</a>\n </li>\n </ul>\n \n\n\n </nav>\n \n\n \n\n</header>\n\n\n <main>\n \n <div class="m-1">\n <img style="max-width: 15%;" src="/static/img/raccoon.jpg">\n </div>\n \n\n \n \n <br>\n \n <div class="row m-2">\n \n \n <div class="card me-2" style="width: 12rem;">\n <img class="card-img-top" src="/static/img/rubic.jpg">\n <div class="card-body">\n <h5 class="card-title">Кубик рубика</h5>\n <p class="card-text">Хороший тренажер мозга</p>\n <a href="/catalog/1/" class="btn btn-primary">Подробнее</a>\n </div>\n </div>\n \n <div class="card me-2" style="width: 12rem;">\n <img class="card-img-top" src="/static/img/keyboard.jpg">\n <div class="card-body">\n <h5 class="card-title">Клавиатура</h5>\n <p class="card-text">Бюджетная механическая клавиатура</p>\n <a href="/catalog/2/" class="btn btn-primary">Подробнее</a>\n </div>\n </div>\n \n <div class="card me-2" style="width: 12rem;">\n <img class="card-img-top" src="/static/img/borjomi.jpg">\n <div class="card-body">\n <h5 class="card-title">Боржоми</h5>\n <p class="card-text">Поздно Вася пить боржоми когда почки отказали</p>\n <a href="/catalog/3/" class="btn btn-primary">Подробнее</a>\n </div>\n </div>\n \n\n </div>\n\n \n\n\n\n </main>\n\n \n\n<footer>\n <div class="navbar navbar-light bg-light fixed-bottom">\n <p> © 2024 Mike Veretennikov </p>\n </div>\n</footer>\n\n </body> \n\n</html>',
    ]
}
