# Generated by Django 4.2.16 on 2024-11-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("feedback", "0002_alter_feedback_name"),
        (
            "feedback",
            "0003_alter_feedback_options",
        ),
    ]

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратная связь",
            },
        ),
    ]
