# Generated by Django 4.2.16 on 2024-11-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратная связь",
            },
        ),
    ]
