# Generated by Django 4.2.16 on 2024-11-06 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("feedback", "0004_feedback_status_statuslog"),
        (
            "feedback",
            "0005_alter_statuslog_options_alter_statuslog_from_status_and_more",
        ),
        ("feedback", "0006_rename_to_status_statuslog_to"),
    ]

    dependencies = [
        (
            "feedback",
            "0002_alter_feedback_name_squashed_0003_alter_feedback_options",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "получено"),
                    ("in_process", "в обработке"),
                    ("replied", "ответ дан"),
                ],
                default="received",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "from_status",
                    models.CharField(db_column="from", max_length=20),
                ),
                ("to", models.CharField(db_column="to", max_length=20)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="feedback.feedback",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "статус лог",
                "verbose_name_plural": "статус логи",
            },
        ),
    ]
