# Generated by Django 4.2.16 on 2024-11-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedback_status_statuslog"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statuslog",
            options={
                "verbose_name": "статус лог",
                "verbose_name_plural": "статус логи",
            },
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="from_status",
            field=models.CharField(db_column="from", max_length=20),
        ),
        migrations.AlterField(
            model_name="statuslog",
            name="to_status",
            field=models.CharField(db_column="to", max_length=20),
        ),
    ]
