# Generated by Django 4.2.16 on 2024-11-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0005_alter_statuslog_options_alter_statuslog_from_status_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuslog",
            old_name="to_status",
            new_name="to",
        ),
    ]
