# Generated by Django 4.2.16 on 2024-11-16 06:51

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    replaces = [
        (
            "feedback",
            "0007_remove_feedback_mail_remove_feedback_name_and_more",
        ),
        ("feedback", "0008_alter_feedback_text_alter_feedbackauthor_name"),
    ]

    dependencies = [
        (
            "feedback",
            "0004_feedback_status_statuslog_squashed_0006_rename_to_status_statuslog_to",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="mail",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="name",
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, help_text="время создания", null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "получено"),
                    ("in_process", "в обработке"),
                    ("replied", "ответ дан"),
                ],
                default="received",
                help_text="статус фидбека",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(help_text="фидбек", max_length=3000),
        ),
        migrations.CreateModel(
            name="FeedbackFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="файл",
                        upload_to=feedback.models.FeedbackFile.get_upload_path,
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(
                help_text="Что вы хотели сообщить?", max_length=3000
            ),
        ),
        migrations.CreateModel(
            name="FeedbackAuthor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="имя", max_length=150, null=True
                    ),
                ),
                ("mail", models.EmailField(help_text="почта", max_length=150)),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to="feedback.feedback",
                    ),
                ),
            ],
        ),
    ]
