# Generated by Django 4.2.16 on 2024-11-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0007_remove_feedback_mail_remove_feedback_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="text",
            field=models.TextField(
                help_text="Что вы хотели сообщить?", max_length=3000
            ),
        ),
        migrations.AlterField(
            model_name="feedbackauthor",
            name="name",
            field=models.CharField(
                blank=True, help_text="имя", max_length=150, null=True
            ),
        ),
    ]
