# Generated by Django 4.2.16 on 2024-11-15 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("users", "0001_initial"),
        ("users", "0002_alter_profile_birthday_alter_profile_image"),
        ("users", "0003_alter_profile_coffee_count_alter_profile_image"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0019_translate_norm_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, help_text="день рождения", null=True
                    ),
                ),
                (
                    "coffee_count",
                    models.PositiveIntegerField(
                        default=0, help_text="счетчик кофе"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="аватарка",
                        null=True,
                        upload_to="uploads/profile_images/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль",
                "verbose_name_plural": "профили",
            },
        ),
    ]
