# Generated by Django 4.2.16 on 2024-11-12 18:19

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True, help_text="день рождения", null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="аватарка",
                null=True,
                upload_to="uploads/profile_images/",
                verbose_name=catalog.models.MainImage,
            ),
        ),
    ]
