# Generated by Django 4.2.16 on 2024-11-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_profile_birthday_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0, help_text="счетчик кофе"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="аватарка",
                null=True,
                upload_to="uploads/profile_images/",
            ),
        ),
    ]
