# Generated by Django 4.2.16 on 2024-11-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"verbose_name": "отзыв", "verbose_name_plural": "отзывы"},
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Неизвестно"),
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                default=3,
                help_text="оценка",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("user_id", "item_id"), name="unique_user_item"
            ),
        ),
    ]
