# Generated by Django 4.2.16 on 2024-11-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_translate_norm_names"),
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="item",
            field=models.ForeignKey(
                help_text="товар",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rating",
                to="catalog.item",
            ),
        ),
    ]
