# Generated by Django 4.2.16 on 2024-11-22 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0002_alter_rating_item"),
        ("rating", "0002_alter_rating_options_alter_rating_score_and_more"),
    ]

    operations = []
