# Generated by Django 4.2.16 on 2024-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0003_merge_20241122_2313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="дата создания",
                null=True,
                verbose_name="дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "Неизвестно"),
                    (1, "Ненависть"),
                    (2, "Неприязнь"),
                    (3, "Нейтрально"),
                    (4, "Обожание"),
                    (5, "Любовь"),
                ],
                default=3,
                help_text="оценка",
                null=True,
                verbose_name="оценка",
            ),
        ),
    ]
