# Generated by Django 4.2.16 on 2024-10-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial_squashed_0002_category_normalized_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.ImageField(
                blank=True,
                upload_to="uploads/",
                verbose_name="главное изображение",
            ),
        ),
    ]
