# Generated by Django 4.2.16 on 2024-10-22 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_item_main_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
    ]
