# Generated by Django 4.2.16 on 2024-10-23 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_mainimage_item_images_item_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item",
                to="catalog.mainimage",
                verbose_name="главное изображение",
            ),
        ),
    ]
