# Generated by Django 4.2.16 on 2024-10-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0004_image_alter_item_images_alter_item_main_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="item_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.item",
                verbose_name="id айтема",
            ),
        ),
    ]
