# Generated by Django 4.2.16 on 2024-10-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_imagemodel_item_main_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemodel",
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.imagemodel",
            ),
        ),
    ]
