# Generated by Django 4.2.16 on 2024-10-25 09:55

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0007_alter_item_text"),
        ("catalog", "0008_remove_item_images_remove_item_main_image_and_more"),
        ("catalog", "0009_galleryimage"),
    ]

    dependencies = [
        ("catalog", "0005_alter_item_images_squashed_0006_alter_item_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=tinymce.models.HTMLField(
                help_text="введите текст",
                validators=[
                    catalog.validators.ValidateMustContain(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
        migrations.RemoveField(
            model_name="item",
            name="images",
        ),
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
        migrations.RemoveField(
            model_name="mainimage",
            name="item_id",
        ),
        migrations.AddField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.item",
                verbose_name="id айтема",
            ),
        ),
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        default=None,
                        upload_to="uploads/",
                        verbose_name="изображения",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.item",
                        verbose_name="id айтема",
                    ),
                ),
            ],
            options={
                "verbose_name": "изображения",
                "verbose_name_plural": "изображения",
            },
        ),
    ]
