# Generated by Django 4.2.16 on 2024-10-29 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0010_alter_mainimage_item"),
        ("catalog", "0011_item_is_on_main"),
        ("catalog", "0012_rename_images_galleryimage_image_and_more"),
    ]

    dependencies = [
        ("catalog", "0007_alter_item_text_squashed_0009_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
                verbose_name="id айтема",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="введите принадлежит ли к главной странице товар",
                verbose_name="принадлежит к главной странице",
            ),
        ),
        migrations.RenameField(
            model_name="galleryimage",
            old_name="images",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
                verbose_name="id айтема",
            ),
        ),
    ]
