# Generated by Django 4.2.16 on 2024-10-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_mainimage_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False,
                help_text="введите принадлежит ли к главной странице товар",
                verbose_name="принадлежит к главной странице",
            ),
        ),
    ]
