# Generated by Django 4.2.16 on 2024-10-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0013_alter_item_category_alter_item_tags"),
        ("catalog", "0014_alter_category_normalized_name_and_more"),
    ]

    dependencies = [
        (
            "catalog",
            "0010_alter_mainimage_item_squashed_0012_rename_images_galleryimage_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="catalog.category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                related_name="items",
                related_query_name="item",
                to="catalog.tag",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(blank=True, default=None, max_length=150),
        ),
    ]
