# Generated by Django 4.2.16 on 2024-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("catalog", "0015_alter_category_normalized_name_and_more"),
        ("catalog", "0016_alter_category_normalized_name_and_more"),
    ]

    dependencies = [
        (
            "catalog",
            "0013_alter_item_category_alter_item_tags_squashed_0014_alter_category_normalized_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True
            ),
        ),
    ]
