# Generated by Django 4.2.16 on 2024-10-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_category_normalized_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                blank=True, default=None, max_length=150, null=True
            ),
        ),
    ]
