# Generated by Django 4.2.16 on 2024-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_translate_norm_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="нормализированное имя",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="введите слаг",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                default=None, upload_to="uploads/", verbose_name="изображение"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="обновлено"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="normalized_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=150,
                null=True,
                verbose_name="нормализированное имя",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="введите слаг",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
